eggd_generate_rd_wgs_workbook  1.0.0
eastgenomics/eggd_generate_wgs_workbook pull request #1
Opened 2024-05-13 09:35 UTC by kjwinfield

Initial PR for eggd_generate_wgs_workbook, an app which takes a GEL JSON and creates a workbook of variants for analysis

Workbook has nine sheets
* Summary sheet with details about the case and family
* Variants sheet with GEL tiering variants
* Extended analysis sheet with Exomiser/de Novo variants (these are only looked at if nothing is found in the GEL tiering sheet)
* STR guidelines sheet with image of guidelines for classifying STRs
* 3 x SNV interpretation sheet, a template to classify an SNV
* 2 x CNV interpretation sheet, a template to classify a CNV

Variants are displayed if they meet the following criteria:
GEL Tiering sheet
* TIER1 SNVs
* TIER2 SNVs
* TIERA/TIER1 CNVs
* TIER1 STRs
Extended analysis sheet
* Exomiser Top 3 ranked variants
    * only displayed if:
        * score >= 0.75
        * variant is not mitochondrial and untiered.
        * variant has not already been reported in GEL tiering sheet.
* DeNovo variants:
    * all variants with a de novo score above the threshold, regardless of tier.

DNAnexus job using current version:
https://platform.dnanexus.com/panx/projects/GjjF4gQ4XQ1XB9GX7b49P7FQ/monitor/job/Gjz45QQ4XQ1bbzXQVfk34V6J

NOTE: Some processes are still fending analyst feedback and have TODOs to explain whether things might change / where there are gaps.

2024-05-13 09:35 UTC, pep8speaks commented
Hello @kjwinfield! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`resources/home/dnanexus/excel_styles.py`](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/7157a5c892a1ae0f9c196f5c26fb54d4c6c9aba0/resources/home/dnanexus/excel_styles.py):

> [Line 12:1](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/7157a5c892a1ae0f9c196f5c26fb54d4c6c9aba0/resources/home/dnanexus/excel_styles.py#L12): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 82:1](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/7157a5c892a1ae0f9c196f5c26fb54d4c6c9aba0/resources/home/dnanexus/excel_styles.py#L82): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 93:17](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/7157a5c892a1ae0f9c196f5c26fb54d4c6c9aba0/resources/home/dnanexus/excel_styles.py#L93): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 111:32](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/7157a5c892a1ae0f9c196f5c26fb54d4c6c9aba0/resources/home/dnanexus/excel_styles.py#L111): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 112:32](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/7157a5c892a1ae0f9c196f5c26fb54d4c6c9aba0/resources/home/dnanexus/excel_styles.py#L112): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 113:32](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/7157a5c892a1ae0f9c196f5c26fb54d4c6c9aba0/resources/home/dnanexus/excel_styles.py#L113): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 114:32](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/7157a5c892a1ae0f9c196f5c26fb54d4c6c9aba0/resources/home/dnanexus/excel_styles.py#L114): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 120:32](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/7157a5c892a1ae0f9c196f5c26fb54d4c6c9aba0/resources/home/dnanexus/excel_styles.py#L120): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 121:32](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/7157a5c892a1ae0f9c196f5c26fb54d4c6c9aba0/resources/home/dnanexus/excel_styles.py#L121): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 122:32](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/7157a5c892a1ae0f9c196f5c26fb54d4c6c9aba0/resources/home/dnanexus/excel_styles.py#L122): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 123:32](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/7157a5c892a1ae0f9c196f5c26fb54d4c6c9aba0/resources/home/dnanexus/excel_styles.py#L123): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 132:32](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/7157a5c892a1ae0f9c196f5c26fb54d4c6c9aba0/resources/home/dnanexus/excel_styles.py#L132): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 133:32](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/7157a5c892a1ae0f9c196f5c26fb54d4c6c9aba0/resources/home/dnanexus/excel_styles.py#L133): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 134:32](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/7157a5c892a1ae0f9c196f5c26fb54d4c6c9aba0/resources/home/dnanexus/excel_styles.py#L134): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 135:32](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/7157a5c892a1ae0f9c196f5c26fb54d4c6c9aba0/resources/home/dnanexus/excel_styles.py#L135): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 139:80](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/7157a5c892a1ae0f9c196f5c26fb54d4c6c9aba0/resources/home/dnanexus/excel_styles.py#L139): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)
> [Line 147:50](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/7157a5c892a1ae0f9c196f5c26fb54d4c6c9aba0/resources/home/dnanexus/excel_styles.py#L147): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace

* In the file [`resources/home/dnanexus/get_variant_info.py`](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/7157a5c892a1ae0f9c196f5c26fb54d4c6c9aba0/resources/home/dnanexus/get_variant_info.py):

> [Line 3:1](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/7157a5c892a1ae0f9c196f5c26fb54d4c6c9aba0/resources/home/dnanexus/get_variant_info.py#L3): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 102:9](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/7157a5c892a1ae0f9c196f5c26fb54d4c6c9aba0/resources/home/dnanexus/get_variant_info.py#L102): [E731](https://duckduckgo.com/?q=pep8%20E731) do not assign a lambda expression, use a def
> [Line 117:17](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/7157a5c892a1ae0f9c196f5c26fb54d4c6c9aba0/resources/home/dnanexus/get_variant_info.py#L117): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 160:5](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/7157a5c892a1ae0f9c196f5c26fb54d4c6c9aba0/resources/home/dnanexus/get_variant_info.py#L160): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 172:9](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/7157a5c892a1ae0f9c196f5c26fb54d4c6c9aba0/resources/home/dnanexus/get_variant_info.py#L172): [E731](https://duckduckgo.com/?q=pep8%20E731) do not assign a lambda expression, use a def
> [Line 285:9](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/7157a5c892a1ae0f9c196f5c26fb54d4c6c9aba0/resources/home/dnanexus/get_variant_info.py#L285): [E731](https://duckduckgo.com/?q=pep8%20E731) do not assign a lambda expression, use a def
> [Line 298:25](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/7157a5c892a1ae0f9c196f5c26fb54d4c6c9aba0/resources/home/dnanexus/get_variant_info.py#L298): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 309:39](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/7157a5c892a1ae0f9c196f5c26fb54d4c6c9aba0/resources/home/dnanexus/get_variant_info.py#L309): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 326:1](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/7157a5c892a1ae0f9c196f5c26fb54d4c6c9aba0/resources/home/dnanexus/get_variant_info.py#L326): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 377:72](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/7157a5c892a1ae0f9c196f5c26fb54d4c6c9aba0/resources/home/dnanexus/get_variant_info.py#L377): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 411:72](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/7157a5c892a1ae0f9c196f5c26fb54d4c6c9aba0/resources/home/dnanexus/get_variant_info.py#L411): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 449:30](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/7157a5c892a1ae0f9c196f5c26fb54d4c6c9aba0/resources/home/dnanexus/get_variant_info.py#L449): [W605](https://duckduckgo.com/?q=pep8%20W605) invalid escape sequence '\('
> [Line 449:35](https [...]

2024-05-15 15:49 UTC, Addy81 requested changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_workbook/1)* status: 0 of 21 files reviewed, 4 unresolved discussions (waiting on @kjwinfield and @mattgarner)

___
*[`dxapp.json` line 23 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_workbook/1#-NxwjEZw6HQNUY4dWaiA:-NxwjEZw6HQNUY4dWaiB:b-cls2qe) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/6e3b5c21eb428530725de4de89f2b8f7c7e37191/dxapp.json#L23)):*
> ```JSON
>       },
>       {
>         "name": "out_dir",
> ```

Could remove since this is built in functionality.
___
*[`dxapp.json` line 52 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_workbook/1#-Nxwj5fG8KnnXZLb4R3n:-Nxwj5fG8KnnXZLb4R3o:b-zax2aq) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/6e3b5c21eb428530725de4de89f2b8f7c7e37191/dxapp.json#L52)):*
> ```JSON
>       },
>       {
>         "name": "obo_path",
> ```

Consider if needed, since you specify he obo_files as an array the path seems less robust.
___
*[`README.md` line 40 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_workbook/1#-NxwkJFO-OpaCuJNOkk3:-NxwkJFO-OpaCuJNOkk4:b-yel9kb) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/6e3b5c21eb428530725de4de89f2b8f7c7e37191/README.md#L40)):*
> ```Markdown
>         * variant is not mitochondrial and untiered.
>         * variant has not already been reported in GEL tiering sheet.
> * DeNovo variants:
> ```

if i'm being picky could this be de novo or does it break anything
___
*[`resources/home/dnanexus/excel_styles.py` line 68 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_workbook/1#-NxwiXzL12u--l_NyIKh:-NxwiXzL12u--l_NyIKi:b-fveuzl) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/6e3b5c21eb428530725de4de89f2b8f7c7e37191/resources/home/dnanexus/excel_styles.py#L68)):*
> ```Python
>             None, adds content to openpxyl workbook
>         '''
>         for col in ['C', 'D', 'M']:
> ```

How confident are we that the order of the columns would remain the same?


<!-- Sent from Reviewable.io -->

2024-05-17 13:24 UTC, mattgarner requested changes
> Reviewed 1 of 21 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_workbook/1)* status: 1 of 21 files reviewed, 8 unresolved discussions (waiting on @chrispyatt and @kjwinfield)

___
*[`dxapp.json` line 1 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_workbook/1#-Ny5hwLVD2RxsbMJWjwj:-Ny5hwLVD2RxsbMJWjwk:brr6xgw) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/6e3b5c21eb428530725de4de89f2b8f7c7e37191/dxapp.json#L1)):*
> ```JSON
> {
> ```

whatsNew :pray: 



_Code quote:_
```JSON
{
```
___
*[`dxapp.json` line 17 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_workbook/1#-Ny5gRr9-LAPGO_ITJ_G:-Ny5gRr9-LAPGO_ITJ_H:bqlj47e) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/6e3b5c21eb428530725de4de89f2b8f7c7e37191/dxapp.json#L17)):*
> ```JSON
>       {
>         "name": "output",
>         "label": "output name prefix for file, if not set will use json input",
> ```

Perhaps `output_name_prefix`is a better name

Having an input named output may be a little confusing :inbox_tray: :outbox_tray: 



_Code quote:_
```JSON
        "name": "output",
        "label": "output name prefix for file, if not set will use json input",
```
___
*[`dxapp.json` line 44 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_workbook/1#-Ny5h9RD3zjsva_LCuyh:-Ny5h9RD3zjsva_LCuyi:b-yz9f39) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/6e3b5c21eb428530725de4de89f2b8f7c7e37191/dxapp.json#L44)):*
> ```JSON
>       },
>       {
>         "name": "mane",
> ```

perhaps `mane_file`?



_Code quote:_
```JSON
mane
```
___
*[`dxapp.json` line 78 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_workbook/1#-Ny5hpSP8gt2YncpuPjY:-Ny5hpSP8gt2YncpuPjZ:b-r3zegi) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/6e3b5c21eb428530725de4de89f2b8f7c7e37191/dxapp.json#L78)):*
> ```JSON
>         "label": "Variant workbook for the given case",
>         "class": "file",
>         "optional": true,
> ```

Is this optional?



_Code quote:_
```JSON
       "optional": true,
```


<!-- Sent from Reviewable.io -->

2024-05-20 17:16 UTC, mattgarner requested changes
> Reviewed 1 of 21 files at r1, 2 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_workbook/1)* status: 4 of 21 files reviewed, 10 unresolved discussions (waiting on @Addy81 and @kjwinfield)

___
*[`README.md` line 17 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_workbook/1#-Ny5j3wa-YhJsfjo2RiB:-Ny5j3wbD2WIqKrsBVMU:blgut1o) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/6e3b5c21eb428530725de4de89f2b8f7c7e37191/README.md#L17)):*
> ```Markdown
> **Inputs**
> Required
> * `json`: a GEL JSON with data to be put into a workbook
> ```

`GEL RD WGS JSON` perhaps?



_Code quote:_
```Markdown
GEL JSON
```
___
*[`resources/home/dnanexus/get_variant_info.py` line 39 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_workbook/1#-NyLyPQQ6MsylBf_bYrk:-NyLyPQR23pdSPIGj4iW:bbysk4p) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/6e3b5c21eb428530725de4de89f2b8f7c7e37191/resources/home/dnanexus/get_variant_info.py#L39)):*
> ```Python
>             if entry['type'] == 'gene':
>                 gene_list.append(entry['geneSymbol'])
>         uniq_genes = list(set(gene_list))
> ```

minor minor nitpick:

is list(set()) necessary here?

how about
```
uniq_genes = set(gene_list)
if len(uniq_genes) == 1:
            gene_symbol = uniq_genes.pop()
        else:
            gene_symbol = str(uniq_genes).strip('{').strip('}')
        return gene_symbol
```



_Code quote:_
```Python
list(set(gene_list))
```


<!-- Sent from Reviewable.io -->

2024-05-20 17:25 UTC, mattgarner reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_workbook/1)* status: 4 of 21 files reviewed, 10 unresolved discussions (waiting on @Addy81 and @kjwinfield)

___
*[`resources/home/dnanexus/get_variant_info.py` line 39 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_workbook/1#-NyLyPQQ6MsylBf_bYrk:-NyM-MVT77srZmaB7Eui:b-sav1tv) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/6e3b5c21eb428530725de4de89f2b8f7c7e37191/resources/home/dnanexus/get_variant_info.py#L39)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

minor minor nitpick:

is list(set()) necessary here?

how about
```
uniq_genes = set(gene_list)
if len(uniq_genes) == 1:
            gene_symbol = uniq_genes.pop()
        else:
            gene_symbol = str(uniq_genes).strip('{').strip('}')
        return gene_symbol
```
</blockquote></details>

I've changed my mind - this might risk introducing non-deterministic behaviour since the order of the set may differ between instances, so converting the set to a str can then yield different results.

Related to this - perhaps you should sort your list to ensure that that always has the genes in the same order, otherwise:

set_a
`{'b', 'a'}`
becomes list
`['b', 'a']`
`str("['b', 'a']")` becomes `'b','a'`

set_b
`{'a', 'b'}`
becomes list
`['a', 'b']`
`str("['a', 'b']")` becomes `'a','b'`


<!-- Sent from Reviewable.io -->

2024-05-20 18:29 UTC, mattgarner reviewed
> Reviewed 12 of 21 files at r1, 1 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_workbook/1)* status: 17 of 21 files reviewed, 10 unresolved discussions (waiting on @Addy81 and @kjwinfield)



<!-- Sent from Reviewable.io -->

2024-05-22 13:14 UTC, chrispyatt requested changes
> Reviewed 14 of 21 files at r1, 3 of 6 files at r2, 3 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_workbook/1)* status: 18 of 22 files reviewed, 9 unresolved discussions (waiting on @Addy81, @kjwinfield, and @mattgarner)

___
*[`resources/home/dnanexus/make_workbook.py` line 220 at r4](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_workbook/1#-NyVR291AeyMdEIvApx0:-NyVR291AeyMdEIvApx1:bdrntog) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/f672f4afe2979dce555af3bc429d4fd936a7a88b/resources/home/dnanexus/make_workbook.py#L220)):*
> ```Python
>         if self.args.obo_files:
>             if version == "v2019_02_12":
>                 obo = "/home/dnanexus/obo_files/hpo_v20190212.obo"
> ```

will these names always be the same?
___
*[`resources/home/dnanexus/tests/test_make_workbook.py` line 68 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_workbook/1#-NyPI8goBkZi-ZefocUb:-NyPI8goBkZi-ZefocUc:b-wie16x) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/6e3b5c21eb428530725de4de89f2b8f7c7e37191/resources/home/dnanexus/tests/test_make_workbook.py#L68)):*
> ```Python
>         assert excel.get_hpo_obo(self) == "/home/dnanexus/obo_files/hpo_v20190212.obo"
> 
>     # @mock.patch('argparse.ArgumentParser.parse_args',
> ```

another TODO?
___
*[`resources/home/dnanexus/tests/test_make_workbook.py` line 122 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_workbook/1#-NyPI1Qb55u0GNqlQytY:-NyPI1Qb55u0GNqlQytZ:b3kte96) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/6e3b5c21eb428530725de4de89f2b8f7c7e37191/resources/home/dnanexus/tests/test_make_workbook.py#L122)):*
> ```Python
>         assert self.summary_content[(3,2)] == "complete"
> 
>     # def test_person_data(self):
> ```

is this a TODO or can it be removed?
___
*[`src/code.sh` line 5 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_workbook/1#-Ny5wh00BmTeVM9BhQbj:-Ny5wh00BmTeVM9BhQbk:b-7n6c14) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/6e3b5c21eb428530725de4de89f2b8f7c7e37191/src/code.sh#L5)):*
> ```Shell
> 
> main() {
>     #mark-section "Setting up and downloading inputs"
> ```

commented out?
___
*[`src/code.sh` line 13 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_workbook/1#-Ny5wjiR9oiuVz3q8IW_:-Ny5wjiR9oiuVz3q8IWa:bvsqwnt) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/6e3b5c21eb428530725de4de89f2b8f7c7e37191/src/code.sh#L13)):*
> ```Shell
>     sudo -H python3 -m pip install --no-index --no-deps packages/*
> 
>     #mark-section "Building arguments"
> ```

commented
___
*[`src/code.sh` line 30 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_workbook/1#-Ny5wlG1Cz78C_4mBgq0:-Ny5wlG1Cz78C_4mBgq1:bvsqwnt) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/6e3b5c21eb428530725de4de89f2b8f7c7e37191/src/code.sh#L30)):*
> ```Shell
>     if [ "$obo_files" ]; then find ~/in/obo_files -type f -name "*" -print0 | xargs -0 -I {} mv {} ~/obo_files; fi
> 
>     #mark-section "Generating workbook"
> ```

commented
___
*[`src/code.sh` line 34 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_workbook/1#-Ny5wmzM1ceHGbSGJHKa:-Ny5wmzM1ceHGbSGJHKb:bvsqwnt) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/6e3b5c21eb428530725de4de89f2b8f7c7e37191/src/code.sh#L34)):*
> ```Shell
>     --json /home/dnanexus/in/json/*json --mane /home/dnanexus/in/mane/* --refseq_tsv /home/dnanexus/in/refseq_tsv/*tsv $args
>     mv *.xlsx /home/dnanexus/out/xlsx_reports
>     #mark-section "Uploading workbook"
> ```

commented


<!-- Sent from Reviewable.io -->

2024-05-23 12:21 UTC, chrispyatt requested changes
> Reviewed 3 of 6 files at r3, 1 of 1 files at r4, 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_workbook/1)* status: all files reviewed, 14 unresolved discussions (waiting on @Addy81, @kjwinfield, and @mattgarner)

___
*[`resources/home/dnanexus/get_variant_info.py` line 43 at r4](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_workbook/1#-Ny_6VdV9-oVnF6EJc4f:-Ny_6VdV9-oVnF6EJc4g:bxpbobd) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/f672f4afe2979dce555af3bc429d4fd936a7a88b/resources/home/dnanexus/get_variant_info.py#L43)):*
> ```Python
>             gene_symbol = uniq_genes.pop()
>         else:
>             gene_symbol = str(uniq_genes).strip('[').strip(']')
> ```

are we ok with this potentially being multiple gene symbols? i.e. should that flag up? If it's fine then I think the doc string should reflect that
___
*[`resources/home/dnanexus/get_variant_info.py` line 78 at r4](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_workbook/1#-Ny_6sIg0wfDXtpcOTgr:-Ny_6sIg0wfDXtpcOTgs:b-7rwrbl) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/f672f4afe2979dce555af3bc429d4fd936a7a88b/resources/home/dnanexus/get_variant_info.py#L78)):*
> ```Python
>         Outputs:
>             highest_af: frequency of the variant in the population with
>             the highest allele frequency of the variant, or 0 if the variant
> ```

"highest allele frequency for that variant" might be slightly clearer
___
*[`resources/home/dnanexus/make_workbook.py` line 471 at r4](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_workbook/1#-Ny_Li5pA5QWkBaAqXGi:-Ny_Li5pA5QWkBaAqXGj:bygc2cu) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/f672f4afe2979dce555af3bc429d4fd936a7a88b/resources/home/dnanexus/make_workbook.py#L471)):*
> ```Python
> 
>         # STRs
>         for str in self.wgs_data["interpretedGenomes"][
> ```

could str be called something else (even just s_t_r)? The diff colours it as if it is a keyword, I think because it looks like str()? Also applies to other functions dealing with STRs as I've read it as "string" a few times.
___
*[`resources/home/dnanexus/make_workbook.py` line 608 at r4](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_workbook/1#-Ny_NBcX-1D3sbNgGiF2:-Ny_NBcX-1D3sbNgGiF3:b-67fhh1) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/f672f4afe2979dce555af3bc429d4fd936a7a88b/resources/home/dnanexus/make_workbook.py#L608)):*
> ```Python
>             for event in snv["reportEvents"]:
>                 if event['deNovoQualityScore'] is not None:
>                     # Threshold for SNVs is 0.0013
> ```

is this likely to change and be in a config? Is there even a config?
___
*[`resources/home/dnanexus/make_workbook.py` line 635 at r4](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_workbook/1#-Ny_NNOk6MZ5eEe-_6Qe:-Ny_NNOk6MZ5eEe-_6Qf:bdga1sn) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/f672f4afe2979dce555af3bc429d4fd936a7a88b/resources/home/dnanexus/make_workbook.py#L635)):*
> ```Python
>             ]["interpretedGenomeData"]["structuralVariants"]:
>             for event in sv["reportEvents"]:
>                 # Threshold for CNVs is 0.02
> ```

as above, will threshold ever change


<!-- Sent from Reviewable.io -->

2024-06-10 06:14 UTC, mattgarner requested changes
> Reviewed 3 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_workbook/1)* status: all files reviewed, 15 unresolved discussions (waiting on @Addy81 and @kjwinfield)

___
*[`resources/home/dnanexus/get_variant_info.py` line 49 at r6](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_workbook/1#-O--ih4Q6dfgBzhl0jig:-O--ih4Q6dfgBzhl0jih:b-av93im) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/a5b65da63bef68ef4735231cfedf9456971546aa/resources/home/dnanexus/get_variant_info.py#L49)):*
> ```Python
>     def convert_tier(tier, var_type):
>         '''
>         Convert tier from GEL tiering variant to include variant type.
> ```

Could the docstring explain why we are doing this? ie. why not use the existing tiers



_Code quote:_
```Python
Convert tier from GEL tiering variant to include variant type.
```
___
*[`resources/home/dnanexus/get_variant_info.py` line 95 at r6](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_workbook/1#-O--jpKe8ZD1SRyAFLIW:-O--jpKe8ZD1SRyAFLIX:b-w1yr6n) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/a5b65da63bef68ef4735231cfedf9456971546aa/resources/home/dnanexus/get_variant_info.py#L95)):*
> ```Python
>         Inputs:
>             variant: (dict): dict extracted from JSON describing single variant
>             m_idx: (int): position within list of variant calls that
> ```

Could we improve these variable names to make it a bit easier to follow
m and f could be male and female or mother and father



_Code quote:_
```Python
 m_idx
```
___
*[`resources/home/dnanexus/get_variant_info.py` line 106 at r6](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_workbook/1#-O--kBK22jW_lbB7pY12:-O--kBK22jW_lbB7pY13:bpzipkr) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/a5b65da63bef68ef4735231cfedf9456971546aa/resources/home/dnanexus/get_variant_info.py#L106)):*
> ```Python
> 
>         inheritance = None
>         maternal = False
> ```

could this variable name be clearer too? (maternal what?)



_Code quote:_
```Python
maternal
```
___
*[`resources/home/dnanexus/get_variant_info.py` line 111 at r6](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_workbook/1#-O--kbg_8wVuAWUSs2Mo:-O--kbg_8wVuAWUSs2Mp:b20m8tn) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/a5b65da63bef68ef4735231cfedf9456971546aa/resources/home/dnanexus/get_variant_info.py#L111)):*
> ```Python
>         inheritance_types = ['alternate_homozygous', 'heterozygous']
> 
>         if m_idx is not None:
> ```

Could be have some comments to explain the logic/method being used to infer inheritance from the data?



_Code quote:_
```Python
if m_idx is not None:
```
___
*[`resources/home/dnanexus/get_variant_info.py` line 123 at r6](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_workbook/1#-O--kNlyCHvMsP2n5iz4:-O--kNlyCHvMsP2n5iz5:b-10djkk) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/a5b65da63bef68ef4735231cfedf9456971546aa/resources/home/dnanexus/get_variant_info.py#L123)):*
> ```Python
>                     paternal = True
> 
>         if maternal is True and paternal is False:
> ```

This would be more pythonic



_Suggestion:_
```Python
if maternal and not paternal:
```
___
*[`resources/home/dnanexus/get_variant_info.py` line 171 at r6](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_workbook/1#-O--lZsZ-jRfd9wih-vu:-O--lZsZ-jRfd9wih-vv:b8q7l2t) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/a5b65da63bef68ef4735231cfedf9456971546aa/resources/home/dnanexus/get_variant_info.py#L171)):*
> ```Python
>             var_dict: (dict) dict of variant information extracted from JSON
>             will be added to a list of dicts for conversion into dataframe.
>         '''
> ```

I'm not quire sure what this function is doing, based on the docstring. 

Sounds like input and output are the same thing (both dicts derived from the json) so I'm not sure what the function does.



_Code quote:_
```Python
        Fill in variant dict for specific STR variant
        Inputs:
            variant (dict): dict extracted from JSON describing single variant
            proband (str): GEL ID for the proband
            columns (list): list of columns to make into keys for variant dict
        Outputs:
            var_dict: (dict) dict of variant information extracted from JSON
            will be added to a list of dicts for conversion into dataframe.
        '''
```


<!-- Sent from Reviewable.io -->

2024-06-10 06:49 UTC, mattgarner requested changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_workbook/1)* status: all files reviewed, 18 unresolved discussions (waiting on @Addy81 and @kjwinfield)

___
*[`resources/home/dnanexus/get_variant_info.py` line 183 at r6](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_workbook/1#-O--mQLbDV9LLRc2-z3J:-O--mQLbDV9LLRc2-z3K:b-lr2idk) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/a5b65da63bef68ef4735231cfedf9456971546aa/resources/home/dnanexus/get_variant_info.py#L183)):*
> ```Python
>         var_dict["Length"] = abs(var_dict["End"] - var_dict["Pos"])
>         var_dict["Type"] = "STR"
>         var_dict["Priority"] = "STR"
> ```

Are we certain that only STR variants will be passed to this function?
(this might become clearer as I read the rest of the code)



_Code quote:_
```Python
        var_dict["Type"] = "STR"
        var_dict["Priority"] = "STR"
```
___
*[`resources/home/dnanexus/get_variant_info.py` line 222 at r6](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_workbook/1#-O--qYV01bcnAfHYC1cB:-O--qYV01bcnAfHYC1cC:b-4mx5cp) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/a5b65da63bef68ef4735231cfedf9456971546aa/resources/home/dnanexus/get_variant_info.py#L222)):*
> ```Python
>         var_dict["Zygosity"] = variant["variantCalls"][pb_idx]["zygosity"]
>         var_dict["Depth"] = variant["variantCalls"][pb_idx]['depthAlternate']
>         var_dict["Gene"] = VariantInfo.get_gene_symbol(variant)
> ```

This took a while to figure out. 

Seemed strange to be calling a get_gene_symbol() method from a VariantInfo class, but have it be a static method, since I'd expect VariantInfo to contain variant info, and so get_gene_symbol would be dependent on the instance of VariantInfo.

However, VariantInfo is actually a collection of methods for getting variant information, but does not store variant information. Maybe the class name needs changing for clarity to describe what the class really is, since it contains no variant info.



_Code quote:_
```Python
VariantInfo.get_gene_symbol(variant)
```
___
*[`resources/home/dnanexus/get_variant_info.py` line 285 at r6](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_workbook/1#-O--u4LV16iWcIJqtMjU:-O--u4LV16iWcIJqtMjV:b-dncj7t) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/a5b65da63bef68ef4735231cfedf9456971546aa/resources/home/dnanexus/get_variant_info.py#L285)):*
> ```Python
>         bronze = []
> 
>         rank = lambda x: x['reportEvents']['vendorSpecificScores']['rank']
> ```

is ["rank"] an integer, and treated as one?



_Code quote:_
```Python
lambda x: x['reportEvents']['vendorSpecificScores']['rank']
```


<!-- Sent from Reviewable.io -->

2024-06-10 07:04 UTC, mattgarner reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_workbook/1)* status: all files reviewed, 18 unresolved discussions (waiting on @Addy81 and @kjwinfield)

___
*[`resources/home/dnanexus/get_variant_info.py` line 322 at r6](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_workbook/1#-O--wjaA1YlNPxf_bsYY:-O--wjaA1YlNPxf_bsYZ:b-bimgxg) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/a5b65da63bef68ef4735231cfedf9456971546aa/resources/home/dnanexus/get_variant_info.py#L322)):*
Note for my understanding/reference. 

Each is a list of dicts, so this becomes a single list to dicts
```
a={"a":1}
b={"b":2}
c={"c":3}
d={"d":4}

x = [a,b]
y = [c]
z = [d]

>>> x + y + z
[{'a': 1}, {'b': 2}, {'c': 3}, {"d":4}]
```



<!-- Sent from Reviewable.io -->

2024-06-10 07:20 UTC, mattgarner requested changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_workbook/1)* status: all files reviewed, 19 unresolved discussions (waiting on @Addy81 and @kjwinfield)

___
*[`resources/home/dnanexus/get_variant_info.py` line 332 at r6](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_workbook/1#-O-0-K6E17WiA3lpmjpJ:-O-0-K6E17WiA3lpmjpK:b-y5n5at) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/a5b65da63bef68ef4735231cfedf9456971546aa/resources/home/dnanexus/get_variant_info.py#L332)):*
> ```Python
>     '''
>     @staticmethod
>     def convert_ensembl_to_refseq(mane, ensembl):
> ```

perhaps this is a more accurate name



_Suggestion:_
```Python
convert_ensembl_to_refseq_mane
```


<!-- Sent from Reviewable.io -->

2024-06-10 07:21 UTC, mattgarner reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_workbook/1)* status: all files reviewed, 19 unresolved discussions (waiting on @Addy81, @chrispyatt, and @kjwinfield)

___
*[`resources/home/dnanexus/make_workbook.py` line 471 at r4](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_workbook/1#-Ny_Li5pA5QWkBaAqXGi:-O-00SBt4j3pvKy6OIk3:b-x55nek) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/f672f4afe2979dce555af3bc429d4fd936a7a88b/resources/home/dnanexus/make_workbook.py#L471)):*
<details><summary><i>Previously, chrispyatt (Chris Pyatt) wrote…</i></summary><blockquote>

could str be called something else (even just s_t_r)? The diff colours it as if it is a keyword, I think because it looks like str()? Also applies to other functions dealing with STRs as I've read it as "string" a few times.
</blockquote></details>

Agree, definitely should not use str as the variable name here


<!-- Sent from Reviewable.io -->

2024-06-11 15:41 UTC, kjwinfield reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_workbook/1)* status: 15 of 22 files reviewed, 19 unresolved discussions (waiting on @Addy81, @chrispyatt, and @mattgarner)

___
*[`dxapp.json` line 23 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_workbook/1#-NxwjEZw6HQNUY4dWaiA:-O-6saTD8wH-nvALT6wZ:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/6e3b5c21eb428530725de4de89f2b8f7c7e37191/dxapp.json#L23)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

Could remove since this is built in functionality.
</blockquote></details>

Done.
___
*[`dxapp.json` line 52 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_workbook/1#-Nxwj5fG8KnnXZLb4R3n:-O-6sbIH2yj0XiJcVpg-:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/6e3b5c21eb428530725de4de89f2b8f7c7e37191/dxapp.json#L52)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

Consider if needed, since you specify he obo_files as an array the path seems less robust.
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/get_variant_info.py` line 43 at r4](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_workbook/1#-Ny_6VdV9-oVnF6EJc4f:-O-6x28yAbC9v1JnvCXf:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/f672f4afe2979dce555af3bc429d4fd936a7a88b/resources/home/dnanexus/get_variant_info.py#L43)):*
<details><summary><i>Previously, chrispyatt (Chris Pyatt) wrote…</i></summary><blockquote>

are we ok with this potentially being multiple gene symbols? i.e. should that flag up? If it's fine then I think the doc string should reflect that
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/get_variant_info.py` line 78 at r4](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_workbook/1#-Ny_6sIg0wfDXtpcOTgr:-O-6shWO7_eh30QTc0S_:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/f672f4afe2979dce555af3bc429d4fd936a7a88b/resources/home/dnanexus/get_variant_info.py#L78)):*
<details><summary><i>Previously, chrispyatt (Chris Pyatt) wrote…</i></summary><blockquote>

"highest allele frequency for that variant" might be slightly clearer
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/get_variant_info.py` line 49 at r6](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_workbook/1#-O--ih4Q6dfgBzhl0jig:-O-6sgfxDLaRX3tlAFVP:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/a5b65da63bef68ef4735231cfedf9456971546aa/resources/home/dnanexus/get_variant_info.py#L49)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Could the docstring explain why we are doing this? ie. why not use the existing tiers
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/get_variant_info.py` line 95 at r6](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_workbook/1#-O--jpKe8ZD1SRyAFLIW:-O-6simY3mDgeXvgmxD7:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/a5b65da63bef68ef4735231cfedf9456971546aa/resources/home/dnanexus/get_variant_info.py#L95)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Could we improve these variable names to make it a bit easier to follow
m and f could be male and female or mother and father
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/get_variant_info.py` line 106 at r6](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_workbook/1#-O--kBK22jW_lbB7pY12:-O-6sjMq6QsE8nnyxXUe:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/a5b65da63bef68ef4735231cfedf9456971546aa/resources/home/dnanexus/get_variant_info.py#L106)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

could this variable name be clearer too? (maternal what?)
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/get_variant_info.py` line 111 at r6](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_workbook/1#-O--kbg_8wVuAWUSs2Mo:-O-6smeh-AYHkAcVmacH:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/a5b65da63bef68ef4735231cfedf9456971546aa/resources/home/dnanexus/get_variant_info.py#L111)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Could be have some comments to explain the logic/method being used to infer inheritance from the data?
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/get_variant_info.py` line 123 at r6](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_workbook/1#-O--kNlyCHvMsP2n5iz4:-O-6snJKAouivQd6ScBv:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/a5b65da63bef68ef4735231cfedf9456971546aa/resources/home/dnanexus/get_variant_info.py#L123)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

This would be more pythonic
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/get_variant_info.py` line 171 at r6](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_workbook/1#-O--lZsZ-jRfd9wih-vu:-O-6x5jT2ot5_-WU7W7B:bzaokcl) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/a5b65da63bef68ef4735231cfedf9456971546aa/resources/home/dnanexus/get_variant_info.py#L171)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

I'm not quire sure what this function is doing, based on the docstring. 

Sounds like input and output are the same thing (both dicts derived from the json) so I'm not sure what the function does.
</blockquote></details>

Done. Add more detail to docstring for this and other variant dict creation functions
___
*[`resources/home/dnanexus/get_variant_info.py` line 183 at r6](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_workbook/1#-O--mQLbDV9LLRc2-z3J:-O-6sqk302-J5KqoHkr4:b-3zjf4o) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/a5b65da63bef68ef4735231cfedf9456971546aa/resources/home/dnanexus/get_variant_info.py#L183)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Are we certain that only STR variants will be passed to this function?
(this might become clearer as I read the rest of the code)
</blockquote></details>

yes, there are separate functions for CNVs, STRs and SNVs
___
*[`resources/home/dnanexus/get_variant_info.py` line 222 at r6](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_workbook/1#-O--qYV01bcnAfHYC1cB:-O-6xDfKEAjLkUtFWfHU:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/a5b65da63bef68ef4735231cfedf9456971546aa/resources/home/dnanexus/get_variant_info.py#L222)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

This took a while to figure out. 

Seemed strange to be calling a get_gene_symbol() method from a VariantInfo class, but have it be a static method, since I'd expect VariantInfo to contain variant info, and so get_gene_symbol would be dependent on the instance of VariantInfo.

However, VariantInfo is actually a collection of methods for getting variant information, but does not store variant information. Maybe the class name needs changing for clarity to describe what the class really is, since it contains no variant info.
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/get_variant_info.py` line 285 at r6](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_workbook/1#-O--u4LV16iWcIJqtMjU:-O-6t-GDATViykBafwIt:b-s5xggw) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/a5b65da63bef68ef4735231cfedf9456971546aa/resources/home/dnanexus/get_variant_info.py#L285)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

is ["rank"] an integer, and treated as one?
</blockquote></deta [...]

2024-06-13 12:30 UTC, mattgarner reviewed
> Reviewed 3 of 7 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_workbook/1)* status: 18 of 22 files reviewed, 9 unresolved discussions (waiting on @Addy81 and @chrispyatt)



<!-- Sent from Reviewable.io -->

2024-06-13 12:40 UTC, chrispyatt requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_workbook/1)* status: 18 of 22 files reviewed, 5 unresolved discussions (waiting on @Addy81, @kjwinfield, and @mattgarner)

___
*[`resources/home/dnanexus/make_workbook.py` line 629 at r7](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_workbook/1#-O-Gb2KzExzDXde1AllB:-O-Gb2KzExzDXde1AllC:b-sgwjwv) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/e8071aa1a0f243a347f77e08aeccf3a2fc563dce/resources/home/dnanexus/make_workbook.py#L629)):*
> ```Python
>             ]["interpretedGenomeData"]["structuralVariants"]:
>             for event in sv["reportEvents"]:
>                 # Threshold for CNVs is 0.02
> ```

Comment should be "Use threshold for CNVs from config"
___
*[`resources/home/dnanexus/make_workbook.py` line 633 at r7](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_workbook/1#-O-Gb1ZZAaa-e2dz0ey5:-O-Gb1ZZAaa-e2dz0ey6:b2ni0jq) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/e8071aa1a0f243a347f77e08aeccf3a2fc563dce/resources/home/dnanexus/make_workbook.py#L633)):*
> ```Python
>                     if (
>                         event['deNovoQualityScore'] >
>                         self.config['denovo_quality_scores']['snv']
> ```

cnv


<!-- Sent from Reviewable.io -->

2024-06-13 12:45 UTC, kjwinfield reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_workbook/1)* status: 17 of 22 files reviewed, 5 unresolved discussions (waiting on @Addy81, @chrispyatt, and @mattgarner)

___
*[`resources/home/dnanexus/make_workbook.py` line 629 at r7](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_workbook/1#-O-Gb2KzExzDXde1AllB:-O-GcLFr3fpK-rDqLq3o:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/e8071aa1a0f243a347f77e08aeccf3a2fc563dce/resources/home/dnanexus/make_workbook.py#L629)):*
<details><summary><i>Previously, chrispyatt (Chris Pyatt) wrote…</i></summary><blockquote>

Comment should be "Use threshold for CNVs from config"
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/make_workbook.py` line 633 at r7](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_workbook/1#-O-Gb1ZZAaa-e2dz0ey5:-O-GcMbUA42W4qMvh6MT:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_wgs_workbook/blob/e8071aa1a0f243a347f77e08aeccf3a2fc563dce/resources/home/dnanexus/make_workbook.py#L633)):*
<details><summary><i>Previously, chrispyatt (Chris Pyatt) wrote…</i></summary><blockquote>

cnv
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-13 12:53 UTC, Addy81 reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_workbook/1)* status: 17 of 22 files reviewed, 2 unresolved discussions (waiting on @chrispyatt and @mattgarner)



<!-- Sent from Reviewable.io -->

2024-06-17 11:57 UTC, mattgarner approved these changes
> Reviewed 4 of 7 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_wgs_workbook/1)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @kjwinfield)



<!-- Sent from Reviewable.io -->

2024-06-17 11:58 UTC, merged